
server:
	g++ -std=c++2a -o server $(mysql_config --cflags) *.cpp $(mysql_config --libs)
clean:
	rm -rf *.o *.a server
#	g++ -std=c++20 -o server *.cpp
#  mysqldump -u admin -p chatdb > /home/fedor/qwe.sql;
